# Analysis of the UN's World Happiness Index with machine learning

Maaike de Jong  
June 2020  
  
See the repository's [README](https://github.com/maaikedj/happiness-machine-learning/blob/master/README.md) file for background and details on the analysis and data.  

### Notebook 3: Supervised machine learning: linear regression
In this notebook I perform a linear regression analysis with scikit-learn, optimising the model with recursive feature elimination. 

In [4]:
# import packages

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.feature_selection import RFE
from sklearn.preprocessing import MinMaxScaler 
from sklearn.preprocessing import RobustScaler 
from sklearn.preprocessing import StandardScaler

In [5]:
# import data

df = pd.read_csv('dfML_clean_tr.csv')
df.head()

Score mean  CO2 emissions (metric tons per capita) log  \
0      7.5114                                    0.675108   
1      7.5110                                    0.772409   
2      7.5460                                    0.845305   
3      7.5410                                    1.017703   
4      7.3506                                    1.182819   

   GDP per capita (current US$) log  \
0                          4.917220   
1                          4.743932   
2                          4.768797   
3                          4.944372   
4                          4.681754   

   Individuals using the Internet (% of population)  Land area (sq. km) log  \
0                                         86.791615                4.596773   
1                                         96.981917                5.001084   
2                                         94.347397                4.624156   
3                                         95.537903                5.562487   
4                                         86.422500                6.958732   

   Life expectancy at birth, total (years)  \
0                                83.026287   
1                                82.454472   
2                                80.440108   
3                                81.969919   
4                                81.732249   

   PM2.5 air pollution, mean annual exposure (micrograms per cubic meter) log  \
0                                           1.066573                            
1                                           0.856043                            
2                                           1.043249                            
3                                           0.886375                            
4                                           0.878417                            

   People using at least basic drinking water services (% of population)  \
0                                         100.000000                       
1                                          99.999999                       
2                                          99.999999                       
3                                         100.000000                       
4                                          99.353377                       

   Population density (people per sq. km of land area) log  \
0                                           2.316057         
1                                           0.517619         
2                                           2.128672         
3                                           1.146877         
4                                           0.590806         

   Population growth (annual %)  Primary education, duration (years)  \
0                      1.052495                                  6.0   
1                      1.133978                                  7.0   
2                      0.531352                                  6.9   
3                      1.059666                                  7.0   
4                      1.078803                                  6.0   

   Proportion of seats held by women in national parliaments (%)  \
0                                             30.800               
1                                             41.440               
2                                             38.311               
3                                             39.903               
4                                             25.365               

   Renewable energy consumption (% of total final energy consumption)  \
0                                          22.946425                    
1                                          76.467214                    
2                                          27.220085                    
3                                          57.320681                    
4                                          22.181059                    

   Secondary education, duration (years)  \
0      

In [ ]:
# make a version of the df with scaled data

scaler = StandardScaler() 

scaled = scaler.fit_transform(df_clean2)
df_scaled = pd.DataFrame(scaled)    

df_scaled.columns = list(df_clean2.columns)

df_scaled.head()    

In [ ]:

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform (X_test)

In [ ]:
# make another one with robust scaler, to compare

scaler2 = RobustScaler() 

scaled2 = scaler2.fit_transform(df_clean2)
df_scaled2 = pd.DataFrame(scaled2)    

df_scaled2.columns = list(df_clean2.columns)

df_scaled2.head() 

In [ ]:
corr = df_scaled2.corr()

plt.figure(figsize=(15,12))
sns.heatmap(corr)

### Linear regression  


In [20]:
# make a version of the df with scaled data

scaler = StandardScaler() 

scaled = scaler.fit_transform(df)
df_scaled = pd.DataFrame(scaled)    

df_scaled.columns = list(df.columns)

df_scaled.head()    

Score mean  CO2 emissions (metric tons per capita) log  \
0    1.919748                                    0.543000   
1    1.919387                                    0.681054   
2    1.950975                                    0.784481   
3    1.946463                                    1.029086   
4    1.774621                                    1.263358   

   GDP per capita (current US$) log  \
0                          1.821566   
1                          1.553274   
2                          1.591770   
3                          1.863604   
4                          1.457005   

   Individuals using the Internet (% of population)  Land area (sq. km) log  \
0                                          1.496033               -0.788665   
1                                          1.853462               -0.304899   
2                                          1.761055               -0.755901   
3                                          1.802812                0.366831   
4                                          1.483086                2.037465   

   Life expectancy at birth, total (years)  \
0                                 1.390823   
1                                 1.322917   
2                                 1.083703   
3                                 1.265375   
4                                 1.237150   

   PM2.5 air pollution, mean annual exposure (micrograms per cubic meter) log  \
0                                          -1.270572                            
1                                          -2.090252                            
2                                          -1.361382                            
3                                          -1.972156                            
4                                          -2.003140                            

   People using at least basic drinking water services (% of population)  \
0                                           0.813178                       
1                                           0.813178                       
2                                           0.813178                       
3                                           0.813178                       
4                                           0.775436                       

   Population density (people per sq. km of land area) log  \
0                                           0.829836         
1                                          -2.166465         
2                                           0.517643         
3                                          -1.118086         
4                                          -2.044531         

   Population growth (annual %)  Primary education, duration (years)  \
0                     -0.325529                             0.359717   
1                     -0.261505                             1.543301   
2                     -0.735013                             1.424943   
3                     -0.319895                             1.543301   
4                     -0.304858                             0.359717   

   Proportion of seats held by women in national parliaments (%)  \
0                                           0.881668               
1                                           1.851343               
2                                           1.566182               
3                                           1.711268               
4                                           0.386350               

   Renewable energy consumption (% of total final energy consumption)  \
0                                          -0.405240                    
1                                           1.408236                    
2                                          -0.260433                    
3                                           0.759483                    
4                                          -0.431173                    

   Secondary education, duration (years)  \
0      

In [22]:
# Split into train and test data
# Run model, average R2 scores over 1000 model runs

score_list = []

for i in range(1000):
    y = df_scaled['Score mean']
    X = df_scaled.drop(['Score mean'], axis=1)
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
    
    LM = linear_model.LinearRegression()
    
    LM.fit(X_train, y_train)
    
    y_pred = LM.predict(X_train)
    r2score_train = r2_score(y_train, y_pred)
    
    y_test_pred = LM.predict(X_test)
    r2score_test = r2_score(y_test, y_test_pred)
    
    score_list.append((r2score_train, r2score_test))

In [23]:
score_df = pd.DataFrame(score_list, columns=('r2score_train', 'r2score_test'))
score_df.head()

r2score_train  r2score_test
0       0.810944      0.704095
1       0.816394      0.712440
2       0.772088      0.875872
3       0.854085      0.358200
4       0.814125      0.740722

In [24]:
print(score_df.mean())

# The scaled (standard scaler) data performs pretty well, although there is an indication of overfitting, which is not surprising with so many variables

r2score_train    0.814376
r2score_test     0.732137
dtype: float64


In [28]:
# Split into train and test data
# Scale date using MinMaxScaler, fit scaler on training data only, use to standardise both training and test sets
# Run model, calculate R2 score
# Average R2 scores over 1000 model runs

score_list = []

for i in range(1000):
    y = df['Score mean']
    X = df.drop(['Score mean'], axis=1)
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
    
    scaler = MinMaxScaler()

    X_train_scaled = scaler.fit_transform(X_train)

    X_test_scaled = scaler.transform(X_test)
    
    LM = linear_model.LinearRegression()
    
    LM.fit(X_train_scaled, y_train)
    
    y_pred = LM.predict(X_train_scaled)
    r2score_train = r2_score(y_train, y_pred)
    
    y_test_pred = LM.predict(X_test_scaled)
    r2score_test = r2_score(y_test, y_test_pred)
    
    score_list.append((r2score_train, r2score_test))

In [29]:
print(LM)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [30]:
score_df = pd.DataFrame(score_list, columns=('r2score_train', 'r2score_test'))
score_df.head()

r2score_train  r2score_test
0       0.810875      0.772388
1       0.806537      0.793215
2       0.816282      0.732907
3       0.820958      0.734765
4       0.817223      0.710996

In [31]:
print(score_df.mean())

# The scaled (standard scaler) data performs pretty well, although there is an indication of overfitting, which is not surprising with so many variables

r2score_train    0.814055
r2score_test     0.733579
dtype: float64


In [ ]:
# define function to run a linear regression model with 1000 cycles and calculate mean R2 socres for the test and train set

def linear_regression(df, test_size):
    
    score_list = []

    for i in range(1000):
        y = df['Score mean']
        X = df.drop(['Score mean'], axis=1)
    
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size)
    
        LM = linear_model.LinearRegression()
    
        LM.fit(X_train, y_train)
    
        y_pred = LM.predict(X_train)
        r2score_train = r2_score(y_train, y_pred)
    
        y_test_pred = LM.predict(X_test)
        r2score_test = r2_score(y_test, y_test_pred)
    
        score_list.append((r2score_train, r2score_test))
    
    score_df = pd.DataFrame(score_list, columns=('r2score_train', 'r2score_test'))
    
    return print(score_df.mean())

In [ ]:
# use function with scaled data (standard scaled)

linear_regression(df_scaled, 0.20)

In [ ]:
# use function with scaled data 2 (robust scaled)
linear_regression(df_scaled2, 0.20)

# results very similar

In [ ]:
# The train data performs well but the test data less so indicating that the model is overfitted
# What happens when we increase the train size and decrease the test size (90-10)?

linear_regression(df_scaled, 0.10)

# performs slightly worse

### Recursive feature elimination

In [ ]:
# now try recursive feature elimination
# eliminate least important variables one by one
# collect R2 scores in dataframe

# first select 15 most important features

selector = RFE(LM, n_features_to_select=1, step=1)

selector = selector.fit(X, y)

selector.ranking_

In [ ]:
# repeat few times (depends on model outcome)

# array([10,  1,  6, 15,  2, 13,  5, 11,  7,  8, 12,  4,  9, 14, 16,  3])
# array([10,  1,  6, 15,  2, 13,  5, 11,  7,  8, 12,  4,  9, 14, 16,  3])
# array([10,  1,  6, 15,  2, 13,  5, 11,  7,  8, 12,  4,  9, 14, 16,  3])
# array([10,  1,  6, 15,  2, 13,  5, 11,  7,  8, 12,  4,  9, 14, 16,  3])

# outcome always the same

In [ ]:
# now try with robust scaled data

score_list = []

for i in range(1000):
    y = df_scaled2['Score mean']
    X = df_scaled2.drop(['Score mean'], axis=1)
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
    
    LM = linear_model.LinearRegression()
    
    LM.fit(X_train, y_train)
    
    y_pred = LM.predict(X_train)
    r2score_train = r2_score(y_train, y_pred)
    
    y_test_pred = LM.predict(X_test)
    r2score_test = r2_score(y_test, y_test_pred)
    
    score_list.append((r2score_train, r2score_test))

score_df = pd.DataFrame(score_list, columns=('r2score_train', 'r2score_test'))

print(score_df.mean())


In [ ]:
selector = RFE(LM, n_features_to_select=1, step=1)

selector = selector.fit(X, y)

selector.ranking_

In [ ]:
# repeat few times (depends on model outcome)

# array([12,  1,  6, 15,  2,  8,  5, 13,  7, 10,  9,  4, 11, 14, 16,  3])
# array([12,  1,  6, 15,  2,  8,  5, 13,  7, 10,  9,  4, 11, 14, 16,  3])
# array([12,  1,  6, 15,  2,  8,  5, 13,  7, 10,  9,  4, 11, 14, 16,  3])

# outcome consistently the same, but slightly different than standard scaled



In [ ]:
df_scaled2.head()

In [ ]:
# Order of importance of variables standard scaled
# up to 7 they're all the same

# 1: GDP per capita (current US$)
# 2: Life expectancy at birth, total (years)
# 3: Refugees country of origin (% of total population
# 4: Renewable energy consumption (% of total final energy consumption)
# 5: People using at least basic drinking water services (% of population)
# 6: Individuals using the Internet (% of population)
# 7: Population growth (annual %)

# 8: Primary education, duration (years)
# 9: Secondary education, duration (years)
# 10: CO2 emissions (metric tons per capita)
# 11: Population density (people per sq. km of land area)
# 12: Proportion of seats held by women in national parliaments (%)
# 13: PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)
# 14: Terrestrial protected areas (% of total land area)
# 15: Land area (sq. km)
# 16: Urban population (% of total population)

In [ ]:
# Order of importance of variables robust scaled
# up to 7 they're all the same

# 1: GDP per capita (current US$)
# 2: Life expectancy at birth, total (years)
# 3: Refugees country of origin (% of total population
# 4: Renewable energy consumption (% of total final energy consumption)
# 5: People using at least basic drinking water services (% of population)
# 6: Individuals using the Internet (% of population)
# 7: Population growth (annual %)

# 8: PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)
# 9: Proportion of seats held by women in national parliaments (%)
# 10: Primary education, duration (years)
# 11: Secondary education, duration (years)
# 12: CO2 emissions (metric tons per capita)
# 13: Population density (people per sq. km of land area)
# 14: Terrestrial protected areas (% of total land area)
# 15: Land area (sq. km)
# 16: Urban population (% of total population)

# overall, robust scaled performs slightly better as a model and it works better with outliers so we're going forward with this one


In [ ]:
dfscaled2_16 = df_scaled2.copy()
dfscaled2_16.head()

In [ ]:
dfscaled2_15 = dfscaled2_16.drop(['Urban population (% of total population)'], axis=1)
dfscaled2_14 = dfscaled2_15.drop(['Land area (sq. km)'], axis=1)
dfscaled2_13 = dfscaled2_14.drop(['Terrestrial protected areas (% of total land area)'], axis=1)
dfscaled2_12 = dfscaled2_13.drop(['Population density (people per sq. km of land area)'], axis=1)
dfscaled2_11 = dfscaled2_12.drop(['CO2 emissions (metric tons per capita)'], axis=1)
dfscaled2_10 = dfscaled2_11.drop(['Secondary education, duration (years)'], axis=1)
dfscaled2_9 = dfscaled2_10.drop(['Primary education, duration (years)'], axis=1)
dfscaled2_8 = dfscaled2_9.drop(['Proportion of seats held by women in national parliaments (%)'], axis=1)
dfscaled2_7 = dfscaled2_8.drop(['PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)'], axis=1)
dfscaled2_6 = dfscaled2_7.drop(['Population growth (annual %)'], axis=1)
dfscaled2_5 = dfscaled2_6.drop(['Individuals using the Internet (% of population)'], axis=1)
dfscaled2_4 = dfscaled2_5.drop(['People using at least basic drinking water services (% of population)'], axis=1)
dfscaled2_3 = dfscaled2_4.drop(['Renewable energy consumption (% of total final energy consumption)'], axis=1)
dfscaled2_2 = dfscaled2_3.drop(['Refugees country of origin (% of total population'], axis=1)
dfscaled2_1 = dfscaled2_2.drop(['Life expectancy at birth, total (years)'], axis=1)


In [ ]:
dfscaled2_2.head()

In [ ]:
linear_regression(dfscaled2_16, 0.20)

In [ ]:
linear_regression(dfscaled2_15, 0.20)

In [ ]:
linear_regression(dfscaled2_14, 0.20)

In [ ]:
linear_regression(dfscaled2_13, 0.20)

In [ ]:
linear_regression(dfscaled2_12, 0.20)

In [ ]:
linear_regression(dfscaled2_11, 0.20)

In [ ]:
linear_regression(dfscaled2_10, 0.20)

In [ ]:
linear_regression(dfscaled2_9, 0.20)

In [ ]:
linear_regression(dfscaled2_8, 0.20)

In [ ]:
linear_regression(dfscaled2_7, 0.20)

In [ ]:
linear_regression(dfscaled2_6, 0.20)

In [ ]:
linear_regression(dfscaled2_5, 0.20)

In [ ]:
linear_regression(dfscaled2_4, 0.20)

In [ ]:
linear_regression(dfscaled2_3, 0.20)

In [ ]:
linear_regression(dfscaled2_2, 0.20)

In [ ]:
linear_regression(dfscaled2_1, 0.20)

In [ ]:
# put into dataframe

data = [[1, 0.724442, 0.701563],
        [2, 0.746336, 0.719748],
        [3, 0.761416, 0.735143],
        [4, 0.769537, 0.736243],
        [5, 0.774668, 0.733050],
        [6, 0.775586, 0.731938],
        [7, 0.783696, 0.736203],
        [8, 0.791826, 0.735551],
        [9, 0.798138, 0.737627],
        [10, 0.798904, 0.740897],
        [11, 0.803905, 0.736488],
        [12, 0.803887, 0.736370],
        [13, 0.809217, 0.744408],
        [14, 0.813000, 0.737465],
        [15, 0.813834, 0.736007],
        [16, 0.814454, 0.733431]]

df_R2_scores = pd.DataFrame(data, columns = ['Nr of variables', 'R2_score_train', 'R2_score_test'])
df_R2_scores

In [ ]:
dfr2_melt = pd.melt(df_R2_scores, id_vars = ['Nr of variables'], value_vars = ['R2_score_train', 'R2_score_test'])
dfr2_melt

In [ ]:
sns.lineplot(x = 'Nr of variables', y = 'value', hue = 'variable', data = dfr2_melt, linewidth=2.5)

In [ ]:
sns.set()
sns.set_style('white')
sns.set_color_codes('pastel')

f, ax = plt.subplots(figsize=(20, 12))

sns.lineplot(x = 'Nr of variables', y = 'value', hue = 'variable', palette = 'Set2', data = dfr2_melt, linewidth=4)

ax.tick_params(axis='both', which='major', labelsize=26) 
ax.tick_params(axis='both', which='minor', labelsize=26)
ax.set_xticks(range(0, 17, 2))

ax.legend(loc="lower right", frameon=True, fontsize = 20)

plt.xlabel('Number of variables', fontsize=30)
plt.ylabel('R2 score', fontsize=30)
plt.suptitle('R2 train and test scores recursive feature elimination', fontsize=36)

sns.despine()